version: "3.9"

services:
  app:
    build: 
      context: .
      dockerfile: Dockerfile
    container_name: myapp
    expose:
      - "5000"
    networks:
      - app-network

  nginx:
    image: nginx:latest
    container_name: nginx-proxy
    ports:
      - "8080:80"
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf:ro
    depends_on:
      - app
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
